spring:
  application:
    name: ticketing-backend
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:keys/jwt-public.pem

server:
  port: 8080

app:
  security:
    cors:
      allowed-origins: http://localhost:5173
    jwt:
      private-key-location: classpath:keys/jwt-private.pem
      expiration-seconds: 3600
